# Generated by Django 4.2.1 on 2024-08-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Контактный email"
                    ),
                ),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(max_length=50, verbose_name="Отчество"),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Клиент сервиса",
                "verbose_name_plural": "Клиенты сервиса",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_of_letter",
                    models.CharField(max_length=100, verbose_name="Тема письма"),
                ),
                ("body_of_letter", models.TextField(verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Сообщение для рассылки",
                "verbose_name_plural": "Сообщения для рассылки",
            },
        ),
        migrations.CreateModel(
            name="Periodicity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, verbose_name="Периодичность рассылки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Периодичность рассылки",
                "verbose_name_plural": "Периодичности рассылок",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="Название рассылки"),
                ),
                (
                    "date_and_time_of_first_mailing",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="дата и время первой отправки рассылки",
                    ),
                ),
                (
                    "mailing_status",
                    models.CharField(
                        default="создана", max_length=20, verbose_name="Статус рассылки"
                    ),
                ),
                (
                    "mailing_start_date",
                    models.DateField(verbose_name="Дата начала рассылки"),
                ),
                (
                    "mailing_end_date",
                    models.DateField(verbose_name="Дата окончания рассылки"),
                ),
                (
                    "time_which_newsletter_sent",
                    models.PositiveIntegerField(
                        verbose_name="Час, в который нужно отправить письмо, пример- 01 или 24"
                    ),
                ),
                (
                    "minute_when_newsletter_should_sent",
                    models.PositiveIntegerField(
                        verbose_name="минута, в которую нужно отправитьсообщение, например 01 или 60"
                    ),
                ),
                (
                    "date_letter_was_sent",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата когда нужно отправить следующее письмо",
                    ),
                ),
                (
                    "customers_of_service",
                    models.ManyToManyField(
                        related_name="customers_of_service",
                        to="mailing.customer",
                        verbose_name="Пользователи сервиса",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailing_list_message",
                        to="mailing.message",
                        verbose_name="Сообщение рассылки",
                    ),
                ),
                (
                    "periodicity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="periodicity",
                        to="mailing.periodicity",
                        verbose_name="Периодичность рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
