# Generated by Django 4.2.1 on 2024-08-26 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_and_time_of_last_mailing_attempt",
                    models.DateTimeField(
                        verbose_name="Дата и время последней попытки рассылки"
                    ),
                ),
                (
                    "attempt_status",
                    models.CharField(
                        max_length=20, verbose_name="статус попытки(успешно/не успешно)"
                    ),
                ),
                (
                    "mail_server_response",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Ответ почтового сервера(если он был)",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                        verbose_name="Связь рассылки и информации о её статусе",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
    ]
