# Generated by Django 4.2.1 on 2024-08-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_mailingattempt_attempt_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailingattempt",
            name="mail_server_response",
        ),
    ]
