# Generated by Django 4.2.1 on 2024-08-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_remove_mailingattempt_mail_server_response"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MailingAttempt",
            new_name="Attempt",
        ),
    ]
