# Generated by Django 4.2.2 on 2024-08-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_rename_mailingattempt_attempt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_disable_mailing", "Может отключить рассылку")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="active",
            field=models.BooleanField(
                default=True, verbose_name="Активна рассылка или нет"
            ),
        ),
    ]
