# Generated by Django 4.2.2 on 2024-08-29 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailing", "0006_alter_mailing_options_mailing_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creator_customer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель клиента",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creator_mailing",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель рассылки",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creator_message",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель сообщения",
            ),
        ),
    ]
