# Generated by Django 4.2.2 on 2024-09-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_customer_creator_mailing_creator_message_creator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_disable_mailing", "Может отключить рассылку"),
                    ("can_view_any_mailing", "can view any mailing lists"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
