# Generated by Django 4.2.2 on 2024-09-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_disable_mailing", "can disable mailing"),
                    ("can_view_any_mailing", "can view any mailing lists"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
