# Generated by Django 4.2.2 on 2025-04-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_alter_mailing_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="periodicity",
        ),
    ]
